//! Real-world-ish MIL corpus: opens a small set of varied MIL programs
//! through the full `Model::open` → `modelAttributes` derivation path,
//! and asserts the parser produces specs consistent with the declared
//! MIL signature.
//!
//! This catches:
//!   * `modelAttributes` shapes we haven't anticipated in the parser
//!     (e.g., a new dtype, a different procedure layout, a depth > 1
//!     tensor that exercises the 5-D rank branch);
//!   * Loss of fidelity between the MIL we feed and what the parser
//!     reports back through `Model::input`/`Model::output`;
//!   * Compile/load failures on shapes that should be accepted.
//!
//! The MIL strings are hand-built rather than generated by
//! `coremltools` — keeps the test self-contained and reproducible
//! across machines without a Python dep.

#![allow(
    clippy::allow_attributes,
    clippy::allow_attributes_without_reason,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::as_conversions,
    clippy::panic,
    clippy::print_stdout,
    clippy::dbg_macro,
    clippy::missing_panics_doc,
    clippy::missing_errors_doc,
    clippy::missing_assert_message,
    clippy::missing_docs_in_private_items,
    clippy::tests_outside_test_module,
    clippy::std_instead_of_core,
    clippy::std_instead_of_alloc,
    clippy::separated_literal_suffix,
    clippy::unseparated_literal_suffix,
    clippy::unreadable_literal,
    clippy::shadow_unrelated,
    clippy::shadow_reuse,
    clippy::shadow_same,
    clippy::min_ident_chars,
    clippy::float_arithmetic,
    clippy::float_cmp,
    clippy::arithmetic_side_effects,
    clippy::integer_division,
    clippy::default_numeric_fallback,
    clippy::pattern_type_mismatch,
    clippy::if_then_some_else_none,
    clippy::single_call_fn,
    clippy::needless_pass_by_value,
    clippy::let_underscore_must_use,
    clippy::let_underscore_untyped,
    clippy::redundant_pub_crate,
    clippy::semicolon_outside_block,
    clippy::semicolon_inside_block,
    clippy::semicolon_if_nothing_returned,
    clippy::print_stderr,
    clippy::clone_on_ref_ptr,
    clippy::integer_division_remainder_used,
    clippy::missing_const_for_fn,
    clippy::use_debug,
    clippy::little_endian_bytes,
    clippy::big_endian_bytes,
    clippy::deref_by_slicing,
    clippy::doc_paragraphs_missing_punctuation,
    clippy::doc_markdown,
    clippy::multiple_unsafe_ops_per_block,
    clippy::undocumented_unsafe_blocks,
    clippy::unused_trait_names,
    clippy::string_slice,
    clippy::cast_possible_wrap,
    clippy::cast_ptr_alignment,
    clippy::assertions_on_result_states,
    clippy::borrow_as_ptr,
    clippy::too_many_lines,
    clippy::unused_result_ok,
    clippy::map_with_unused_argument_over_ranges,
    clippy::ignored_unit_patterns,
    clippy::unreachable,
    clippy::decimal_literal_representation,
    clippy::single_char_pattern,
    clippy::cast_precision_loss,
    reason = "integration tests use idiomatic `.unwrap()` / indexing / `as` / \
              `println!` — assertion failure IS the test failure mode"
)]

mod common;

use ane_bridge::{Dtype, Model, OpenOptions};
use common::Fixture;

/// Identity-style MIL: `y = cast(fp32, cast(fp16, x))` with caller-
/// chosen input/output dtype + shape declared in the func signature.
fn build_identity_mil(token: &str, dtype: &str, shape: &[i64]) -> String {
    let shape_str = shape
        .iter()
        .map(ToString::to_string)
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        r#"program(1.3)
[buildInfo = dict<string, string>({{{{"coremlc-component-MIL", "3510.2.1"}}, {{"coremlc-version", "3505.4.1"}}, {{"coremltools-component-milinternal", ""}}, {{"coremltools-version", "9.0"}}, {{"ane-bridge-corpus", "{token}"}}}})]
{{
    func main<ios18>(tensor<{dtype}, [{shape_str}]> x) {{
        string td16 = const()[name = string("td16"), val = string("fp16")];
        tensor<fp16, [{shape_str}]> x16 = cast(dtype = td16, x = x)[name = string("x16")];
        string td_out = const()[name = string("td_out"), val = string("{dtype}")];
        tensor<{dtype}, [{shape_str}]> y = cast(dtype = td_out, x = x16)[name = string("y")];
    }} -> (y);
}}
"#
    )
}

/// Dual-input dual-output identity: `ya = id(a)`, `yb = id(b)`. Shapes
/// can differ between the two pairs.
fn build_dual_io_mil(token: &str, shape_a: &[i64], shape_b: &[i64]) -> String {
    let sa = shape_a
        .iter()
        .map(ToString::to_string)
        .collect::<Vec<_>>()
        .join(", ");
    let sb = shape_b
        .iter()
        .map(ToString::to_string)
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        r#"program(1.3)
[buildInfo = dict<string, string>({{{{"coremlc-component-MIL", "3510.2.1"}}, {{"coremlc-version", "3505.4.1"}}, {{"coremltools-component-milinternal", ""}}, {{"coremltools-version", "9.0"}}, {{"ane-bridge-corpus", "{token}"}}}})]
{{
    func main<ios18>(tensor<fp32, [{sa}]> a, tensor<fp32, [{sb}]> b) {{
        string td16 = const()[name = string("td16"), val = string("fp16")];
        tensor<fp16, [{sa}]> a16 = cast(dtype = td16, x = a)[name = string("a16")];
        tensor<fp16, [{sb}]> b16 = cast(dtype = td16, x = b)[name = string("b16")];
        string td32 = const()[name = string("td32"), val = string("fp32")];
        tensor<fp32, [{sa}]> ya = cast(dtype = td32, x = a16)[name = string("ya")];
        tensor<fp32, [{sb}]> yb = cast(dtype = td32, x = b16)[name = string("yb")];
    }} -> (ya, yb);
}}
"#
    )
}

/// Write the given MIL + a placeholder weights blob to a fresh
/// tempdir and return the paths.
fn write_fixture(mil: &str) -> Fixture {
    let dir = tempfile::tempdir().expect("tempdir");
    let mil_path = dir.path().join("model.mil");
    let wts_path = dir.path().join("weights.bin");
    std::fs::write(&mil_path, mil).expect("write MIL");
    std::fs::write(&wts_path, b"\x00").expect("write weights");
    Fixture {
        _dir: dir,
        mil: mil_path,
        weights: wts_path,
    }
}

#[derive(Clone)]
struct Case {
    label: &'static str,
    mil: String,
    expected_inputs: Vec<(&'static str, Dtype, Vec<i64>)>,
    expected_outputs: Vec<(&'static str, Dtype, Vec<i64>)>,
}

fn corpus() -> Vec<Case> {
    use Dtype::{Fp16, Fp32};
    let mut tok = 0_u32;
    let mut next_token = || {
        tok += 1;
        format!("corpus-{tok}")
    };

    vec![
        Case {
            label: "fp32-1x64x1x16",
            mil: build_identity_mil(&next_token(), "fp32", &[1, 64, 1, 16]),
            expected_inputs: vec![("x", Fp32, vec![1, 64, 1, 16])],
            expected_outputs: vec![("y", Fp32, vec![1, 64, 1, 16])],
        },
        Case {
            label: "fp16-1x64x1x16",
            mil: build_identity_mil(&next_token(), "fp16", &[1, 64, 1, 16]),
            expected_inputs: vec![("x", Fp16, vec![1, 64, 1, 16])],
            expected_outputs: vec![("y", Fp16, vec![1, 64, 1, 16])],
        },
        Case {
            label: "fp32-2x32x4x32",
            mil: build_identity_mil(&next_token(), "fp32", &[2, 32, 4, 32]),
            expected_inputs: vec![("x", Fp32, vec![2, 32, 4, 32])],
            expected_outputs: vec![("y", Fp32, vec![2, 32, 4, 32])],
        },
        Case {
            label: "fp32-1x16x1x16-tall-channel",
            mil: build_identity_mil(&next_token(), "fp32", &[1, 16, 1, 16]),
            expected_inputs: vec![("x", Fp32, vec![1, 16, 1, 16])],
            expected_outputs: vec![("y", Fp32, vec![1, 16, 1, 16])],
        },
        Case {
            label: "dual-io-same-shape",
            mil: build_dual_io_mil(&next_token(), &[1, 64, 1, 16], &[1, 64, 1, 16]),
            expected_inputs: vec![
                ("a", Fp32, vec![1, 64, 1, 16]),
                ("b", Fp32, vec![1, 64, 1, 16]),
            ],
            expected_outputs: vec![
                ("ya", Fp32, vec![1, 64, 1, 16]),
                ("yb", Fp32, vec![1, 64, 1, 16]),
            ],
        },
        Case {
            label: "dual-io-asymmetric",
            mil: build_dual_io_mil(&next_token(), &[1, 32, 1, 16], &[1, 64, 1, 8]),
            expected_inputs: vec![
                ("a", Fp32, vec![1, 32, 1, 16]),
                ("b", Fp32, vec![1, 64, 1, 8]),
            ],
            expected_outputs: vec![
                ("ya", Fp32, vec![1, 32, 1, 16]),
                ("yb", Fp32, vec![1, 64, 1, 8]),
            ],
        },
    ]
}

#[test]
fn corpus_matches_framework_schema() {
    let cases = corpus();
    for case in cases {
        let fx = write_fixture(&case.mil);
        let opts = OpenOptions::new(fx.mil_path(), fx.weights_path());
        let model = match Model::open(&opts) {
            Ok(m) => m,
            Err(e) => {
                // Compile/Load failures here mean the *framework*
                // rejected the MIL — not a parser bug, but worth
                // surfacing in the test report.
                panic!("[{}] Model::open failed: {e}", case.label);
            }
        };
        let nin = usize::try_from(model.num_inputs()).expect("non-negative input count");
        let nout = usize::try_from(model.num_outputs()).expect("non-negative output count");
        assert_eq!(
            nin,
            case.expected_inputs.len(),
            "[{}] input count: got {nin}, want {}",
            case.label,
            case.expected_inputs.len(),
        );
        assert_eq!(
            nout,
            case.expected_outputs.len(),
            "[{}] output count: got {nout}, want {}",
            case.label,
            case.expected_outputs.len(),
        );
        for (i, (name, dt, shape)) in case.expected_inputs.iter().enumerate() {
            let idx = i32::try_from(i).expect("input index fits in i32");
            let got = model
                .input(idx)
                .unwrap_or_else(|| panic!("[{}] input {i} missing", case.label));
            assert_eq!(got.name(), *name, "[{}] input {i} name", case.label);
            assert_eq!(got.dtype(), *dt, "[{}] input {i} dtype", case.label);
            assert_eq!(got.shape(), &shape[..], "[{}] input {i} shape", case.label);
        }
        for (i, (name, dt, shape)) in case.expected_outputs.iter().enumerate() {
            let idx = i32::try_from(i).expect("output index fits in i32");
            let got = model
                .output(idx)
                .unwrap_or_else(|| panic!("[{}] output {i} missing", case.label));
            assert_eq!(got.name(), *name, "[{}] output {i} name", case.label);
            assert_eq!(got.dtype(), *dt, "[{}] output {i} dtype", case.label);
            assert_eq!(got.shape(), &shape[..], "[{}] output {i} shape", case.label);
        }
    }
}
