# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Derive the Espresso C-ABI binding surface from the live framework.

The framework is the source of truth, not hand-copied notes. This runs
`dyld_info -exports` on Espresso.framework, keeps the exported plain-C symbols
(`espresso_*` and `e5rt_*`), and drops the 5,800+ C++ symbols that can't be
expressed in a C ABI. It writes two artifacts and is safe to re-run after an
OS update (output is sorted / deterministic):

  - tools/espresso/symbols.txt                       human inventory + counts
  - rust/ane-bridge-sys/src/espresso_symbols.rs      pub const name arrays +
                                                     a full-surface resolution test

Usage:
  uv run tools/espresso/derive.py            # derive from the default framework
  uv run tools/espresso/derive.py --check    # fail if the checked-in output is stale
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

FRAMEWORK = "/System/Library/PrivateFrameworks/Espresso.framework/Espresso"
ROOT = Path(__file__).resolve().parents[2]
SYMBOLS_TXT = ROOT / "tools" / "espresso" / "symbols.txt"
GENERATED_RS = ROOT / "rust" / "ane-bridge-sys" / "src" / "espresso_symbols.rs"

_IDENT = re.compile(r"(espresso|e5rt)_[A-Za-z0-9_]+\Z")


def exported_symbols(framework: str) -> set[str]:
    """Return the exported symbol names (leading underscore stripped)."""
    proc = subprocess.run(
        ["dyld_info", "-exports", framework],
        capture_output=True,
        text=True,
        check=True,
    )
    names: set[str] = set()
    for line in proc.stdout.splitlines():
        parts = line.split()
        if not parts:
            continue
        name = parts[-1]
        if name.startswith("_"):
            name = name[1:]
        names.add(name)
    return names


def categorize(names: set[str]) -> tuple[list[str], list[str]]:
    """Split into sorted (espresso_*, e5rt_*) plain-C identifier lists."""
    espresso = sorted(n for n in names if n.startswith("espresso_") and _IDENT.fullmatch(n))
    e5rt = sorted(n for n in names if n.startswith("e5rt_") and _IDENT.fullmatch(n))
    return espresso, e5rt


def render_inventory(espresso: list[str], e5rt: list[str]) -> str:
    lines = [
        "# Espresso.framework — exported C-ABI symbol inventory",
        "#",
        "# Generated by tools/espresso/derive.py from the live framework export",
        "# trie (dyld_info -exports). C++ symbols are excluded. Re-run to refresh.",
        "#",
        f"# espresso_* : {len(espresso)}",
        f"# e5rt_*     : {len(e5rt)}",
        f"# total      : {len(espresso) + len(e5rt)}",
        "",
        "## espresso_*",
        *espresso,
        "",
        "## e5rt_*",
        *e5rt,
        "",
    ]
    return "\n".join(lines)


def _const(name: str, doc: str, symbols: list[str]) -> str:
    body = "\n".join(f'    c"{s}",' for s in symbols)
    return f"/// {doc}\npub const {name}: &[&CStr] = &[\n{body}\n];\n"


def render_rust(espresso: list[str], e5rt: list[str]) -> str:
    header = (
        "//! Generated inventory of Espresso's exported C symbols.\n"
        "//!\n"
        "//! Do not edit by hand — regenerate with `tools/espresso/derive.py`,\n"
        "//! which reads the live framework export trie via `dyld_info`. The\n"
        "//! 5,800+ C++ symbols are omitted; these plain-C entry points are the\n"
        "//! surface the bridge can bind.\n"
        "\n"
        "use core::ffi::CStr;\n"
        "\n"
    )
    esp = _const("ESPRESSO", "Exported `espresso_*` C symbols.", espresso)
    e5 = _const("E5RT", "Exported `e5rt_*` C symbols.", e5rt)
    test = (
        "\n"
        "#[cfg(test)]\n"
        "mod tests {\n"
        "    use super::{E5RT, ESPRESSO};\n"
        "    use core::ffi::{c_char, c_int, c_void};\n"
        "\n"
        '    unsafe extern "C" {\n'
        "        fn dlopen(path: *const c_char, mode: c_int) -> *mut c_void;\n"
        "        fn dlsym(handle: *mut c_void, symbol: *const c_char) -> *mut c_void;\n"
        "    }\n"
        "\n"
        "    /// Every inventoried symbol must resolve in the live framework —\n"
        "    /// the full-surface canary, regenerated alongside the lists.\n"
        "    ///\n"
        "    /// Ignored by default: the inventory is an OS snapshot, so it only\n"
        "    /// holds on the OS it was derived from. Run on a matching machine\n"
        "    /// with `cargo test -p ane-bridge-sys -- --ignored`.\n"
        '    #[ignore = "Espresso export set is an OS snapshot; run with --ignored on the derivation OS"]\n'
        "    #[test]\n"
        "    fn full_surface_resolves() {\n"
        "        const RTLD_NOW: c_int = 2;\n"
        "        // SAFETY: a constant, valid C path string; dlopen reads it and\n"
        "        // returns a handle or null. The framework is already linked, so\n"
        "        // this re-references the loaded image.\n"
        "        let handle = unsafe {\n"
        '            dlopen(c"/System/Library/PrivateFrameworks/Espresso.framework/Espresso".as_ptr(), RTLD_NOW)\n'
        "        };\n"
        '        assert!(!handle.is_null(), "dlopen Espresso.framework failed");\n'
        "        for &name in ESPRESSO.iter().chain(E5RT) {\n"
        "            // SAFETY: `handle` is a live dlopen handle; `name` is a\n"
        "            // valid, NUL-terminated C string. dlsym only reads both.\n"
        "            let sym = unsafe { dlsym(handle, name.as_ptr()) };\n"
        '            assert!(!sym.is_null(), "Espresso symbol not found: {name:?}");\n'
        "        }\n"
        "    }\n"
        "}\n"
    )
    return header + esp + "\n" + e5 + test


def main() -> int:
    check = "--check" in sys.argv[1:]
    names = exported_symbols(FRAMEWORK)
    espresso, e5rt = categorize(names)
    if not espresso or not e5rt:
        print("error: no espresso_*/e5rt_* symbols found — wrong framework path?", file=sys.stderr)
        return 1

    inventory = render_inventory(espresso, e5rt)
    rust = render_rust(espresso, e5rt)

    if check:
        stale = []
        if not SYMBOLS_TXT.exists() or SYMBOLS_TXT.read_text() != inventory:
            stale.append(str(SYMBOLS_TXT.relative_to(ROOT)))
        if not GENERATED_RS.exists() or GENERATED_RS.read_text() != rust:
            stale.append(str(GENERATED_RS.relative_to(ROOT)))
        if stale:
            print("stale (re-run derive.py): " + ", ".join(stale), file=sys.stderr)
            return 1
        print(f"up to date: {len(espresso)} espresso_*, {len(e5rt)} e5rt_*")
        return 0

    SYMBOLS_TXT.write_text(inventory)
    GENERATED_RS.write_text(rust)
    print(f"wrote {len(espresso)} espresso_* + {len(e5rt)} e5rt_* symbols")
    print(f"  {SYMBOLS_TXT.relative_to(ROOT)}")
    print(f"  {GENERATED_RS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
